export const INSERT_APPOINTMENT = "INSERT_APPOINTMENT";
export const LIST_APPOINTMENTS = "LIST_APPOINTMENTS";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const FIND_APPOINTMENT = "FIND_APPOINTMENT";